# Generated by Django 4.2.10 on 2024-03-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="vibe_gif",
            field=models.URLField(default=""),
        ),
    ]
