# Generated by Django 4.2.10 on 2024-03-05 10:42

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Door",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.CharField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unlocked", "Unlocked"),
                            ("locked", "Locked"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=255,
                    ),
                ),
                ("external_id", models.CharField(unique=True)),
                ("output_number", models.CharField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
