# Generated by Django 4.2.13 on 2024-10-17 19:01

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoorLog",
            fields=[
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("unlocked", "Unlocked"), ("locked", "Locked")],
                        max_length=255,
                    ),
                ),
                ("user_email", models.CharField()),
                ("user_first_name", models.CharField()),
                ("user_last_name", models.CharField()),
                (
                    "door",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="doors.door"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
