# Generated by Django 4.2.10 on 2024-03-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="starting_notification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
