# Generated by Django 4.2.13 on 2024-05-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0002_slackmessage_slack_ts_slackreaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackreaction",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
