# Generated by Django 4.2.13 on 2024-05-14 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("slack", "0003_slackreaction_raw_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slackmessage",
            name="external_id",
        ),
    ]
