---

- name: Install dependencies
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Add Docker gpg key
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add apt repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    update_cache: yes
    state: present

- name: Install Docker
  package:
    name: "{{ docker_package }}"
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Add given user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install Docker SDK for Python
  pip:
    name: docker

- name: Start docker
  service:
    name: docker
    state: started
