# Global vars
DOMAIN_NAME: "bonfire.betashack.se"
RABBITMQ_USER: "devrabbitmquser"
RABBITMQ_PASSWORD: "{{ vault_RABBITMQ_PASSWORD }}"

uwsgi_env:
  ALLOWED_HOSTS: "{{ DOMAIN_NAME }}"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://127.0.0.1:3000"

  # Nginx-gen vars
  VIRTUAL_HOST: "{{ DOMAIN_NAME }}"
  VIRTUAL_PORT: "3030"
  VIRTUAL_PROTO: "uwsgi"

django_env:
  DOMAIN_NAME: "{{ DOMAIN_NAME }}"
  ENV: "DEV"

  # Django vars
  DEBUG: "False"
  USE_DEBUG: "False"
  SECRET_KEY: "{{ vault_SECRET_KEY }}"
  DEFAULT_FILE_STORAGE: "django_s3_storage.storage.S3Storage"
  
  # Database vars
  DB_USER: "bonfire"
  DB_PASSWORD: "{{ vault_DB_PASSWORD }}"
  DB_HOST: "dev-20240229160915087900000001.ctkwgoo6ao0h.eu-north-1.rds.amazonaws.com"
  DB_NAME: "bonfire"

  # Static files
  STATIC_ROOT: "/var/www/static/"
  STATICFILES_STORAGE: "whitenoise.storage.CompressedManifestStaticFilesStorage"
  
  # Celery vars
  REDIS_URL: "redis://redis:6379/2"
  CELERY_BROKER_URL: "pyamqp://{{ RABBITMQ_USER }}:{{ RABBITMQ_PASSWORD }}@rabbitmq:5672"

  # 2FA vars
  OTP_TOTP_ISSUER: "bonfire Dev"

  # S3 storage
  AWS_ACCESS_KEY_ID: "AKIA6ODU53RWWLKUX7QI"
  AWS_SECRET_ACCESS_KEY: "{{ vault_AWS_SECRET_ACCESS_KEY }}"
  AWS_REGION: "eu-north-1"
  AWS_S3_BUCKET_NAME: "bonfire-dev-media"

  # Flex
  FLEX_API_URL: "https://flexykey.se/MobileApp.aspx/"
  FLEX_API_USER: "admin@appshack.se"
  FLEX_API_PASSWORD: "{{ vault_FLEX_API_PASSWORD }}"

  # Google
  GOOGLE_WHITELIST_DOMAIN: "appshack.se"
  GOOGLE_APPLICATION_CREDENTIALS: "{{ GOOGLE_CREDENTIALS_PATH }}/google_credentials.json"

  # JWT
  ACCESS_TOKEN_LIFETIME_MINUTES: "1440"
  REFRESH_TOKEN_LIFETIME_MINUTES: "129600"

  # Slack
  SLACK_TOKEN: "{{ vault_SLACK_TOKEN }}"