---

- name: Set up python3
  hosts: dev, prod
  become: yes
  tasks:
    - name: Install base packages
      apt:
        force_apt_get: True
        update_cache: yes
        pkg:
          - python3
          - python3-pip
    - name: Install pip requirements
      pip:
        name:
          - pip
          - awscli
        state: latest

- name: Install docker
  hosts: dev, prod
  become: yes
  roles:
    - install-docker
